# Site settings
title: Jekyll for documentation
email: julien@sigerr.org

description: > # this template is made for documentation.
    If you work in IT, you must write documentation but you
    probably hate Confluence and random wiki software.
    We want git. we want markdown. We don't want no weird shit.

baseurl: "/jekyll-for-documentation" # the subpath of your site, e.g. /blog/
url: "http://www.sigerr.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ["bower.json", "bower_components", "Gemfile", "Gemfile.lock"]

sass:
    load_paths:
        - _sass
    style: compressed
